//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainingsql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        public int idSupplies { get; set; }
        public string Type { get; set; }
        public int Weight { get; set; }
        public int idStock { get; set; }
        public int idProvider { get; set; }
        public int idProduct { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
